### ISSUE TITLE
Can this solution apply for function?

### ISSUE THREAD

**Issue by gianghad** [KSXGitHub/pipe-trait#31]
When I use pipe in another language I don't want it to compile immediately, just want to create a new function. Ex:

```
fn add1(a: usize) -> usize {
    a + 1
}

fn multiple(a: usize) -> usize {
    a * 2
}
```

Now I want a new function that will add1 first then multiple. Is there any way we can do it like this
`
  let newFunc = add1.pipe(multiple)
`

**Comment by KSXGitHub** [comment]
Do you have any problem with closure?

```rust
let new_func = |a: usize| a.pipe(add1).pipe(multiple);
```

**Comment by gianghad** [comment]
Hey, that's a good one. I come from another language with a different approach. This is cool. Thanks
